/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.*;
import controller.ListaC;
import data.ConexaoBD;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Cadastros;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Tabela;

/**
 *
 * @author Marcelo
 */
public class Cadastro extends javax.swing.JFrame {

    ListaC l = new ListaC();
    Cadastros cad;
    ConexaoBD conex;

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        try {
            conex = new ConexaoBD();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        cad = new Cadastros();
        preencherTabela("select * from Cadastros order by cod_cadastro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadUsu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelSobrenome = new javax.swing.JLabel();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelConfSenha = new javax.swing.JLabel();
        jPasswordFieldConfSenha = new javax.swing.JPasswordField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastro = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelFundoCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelCadUsu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelCadUsu.setText("Cadastro de Usuários");
        getContentPane().add(jLabelCadUsu);
        jLabelCadUsu.setBounds(10, 0, 360, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/outfit.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 10, 190, 85);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 90, 665, 10);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome.setText("   Nome:");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(0, 130, 60, 25);

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(60, 130, 130, 25);

        jLabelSobrenome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSobrenome.setText("       Sobrenome:");
        getContentPane().add(jLabelSobrenome);
        jLabelSobrenome.setBounds(210, 130, 110, 25);

        jTextFieldSobrenome.setEnabled(false);
        getContentPane().add(jTextFieldSobrenome);
        jTextFieldSobrenome.setBounds(320, 130, 130, 25);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUsuario.setText(" Usuário:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(0, 160, 60, 25);

        jTextFieldUsuario.setEnabled(false);
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(60, 160, 130, 25);

        jLabelID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelID.setText("    ID:");
        getContentPane().add(jLabelID);
        jLabelID.setBounds(280, 160, 40, 25);

        jTextFieldID.setEnabled(false);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldID);
        jTextFieldID.setBounds(320, 160, 130, 25);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSenha.setText("   Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(0, 190, 60, 25);

        jPasswordFieldSenha.setEnabled(false);
        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(60, 190, 130, 25);

        jLabelConfSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelConfSenha.setText("Confirmar senha:");
        getContentPane().add(jLabelConfSenha);
        jLabelConfSenha.setBounds(210, 190, 110, 25);

        jPasswordFieldConfSenha.setEnabled(false);
        getContentPane().add(jPasswordFieldConfSenha);
        jPasswordFieldConfSenha.setBounds(320, 190, 130, 25);

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setText("     Email:");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(0, 220, 60, 25);

        jTextFieldEmail.setEnabled(false);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(60, 220, 250, 25);

        jButtonPrimeiro.setText("<<");
        jButtonPrimeiro.setToolTipText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrimeiro);
        jButtonPrimeiro.setBounds(340, 230, 70, 25);

        jButtonAnterior.setText("<");
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnterior);
        jButtonAnterior.setBounds(420, 230, 70, 25);

        jButtonProximo.setText(">");
        jButtonProximo.setToolTipText("Próximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProximo);
        jButtonProximo.setBounds(500, 230, 70, 25);

        jButtonUltimo.setText(">>");
        jButtonUltimo.setToolTipText("Último");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUltimo);
        jButtonUltimo.setBounds(580, 230, 70, 25);

        jTableCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCadastro);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 268, 645, 220);

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(20, 500, 82, 25);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(110, 500, 82, 25);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(200, 500, 82, 25);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(290, 500, 82, 25);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(470, 500, 82, 25);

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setEnabled(false);
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(380, 500, 82, 25);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(560, 500, 82, 25);

        jLabelFundoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundoCadastro);
        jLabelFundoCadastro.setBounds(0, 0, 670, 570);

        setSize(new java.awt.Dimension(671, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        //l.gravar();
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    String sql = ("insert into Cadastros(cod_cadastro,nome_cadastro,sobrenome_cadastro,usuario_cadastro,senha_cadastro,confsenha_cadastro,email_cadastro) values(?,?,?,?,?,?,?)");
                    PreparedStatement pst = conex.getConexaoBD().prepareStatement(sql);
                    pst.setInt(1, Integer.parseInt(jTextFieldID.getText()));
                    pst.setString(2, jTextFieldNome.getText());
                    pst.setString(3, jTextFieldSobrenome.getText());
                    pst.setString(4, jTextFieldUsuario.getText());
                    pst.setString(5, jPasswordFieldSenha.getText());
                    pst.setString(6, jPasswordFieldConfSenha.getText());
                    pst.setString(7, jTextFieldEmail.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                    jButtonNovoActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro:\n" + ex.getMessage());
        }
        preencherTabela("select * from Cadastros order by cod_cadastro");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        /*if (l.localizar(Integer.parseInt(jTextFieldID.getText())) == null) {
            JOptionPane.showMessageDialog(this, "Cadastro não encontrado");
        } else {
            JOptionPane.showMessageDialog(this, "Cadastro encontrado");
            exibirCadastro(l.localizar(Integer.parseInt(jTextFieldID.getText())));
        }*/
        cad.setPesquisa(jTextFieldID.getText());
        conex.getConexaoBD();
        conex.executaSQL("select * from Cadastros where cod_cadastro like '%" + cad.getPesquisa() + "%'");
        try {
            conex.getRs().first();
            cad.setId((conex.getRs().getInt("cod_cadastro")));
            cad.setNome(conex.getRs().getString("nome_cadastro"));
            cad.setSobrenome(conex.getRs().getString("sobrenome_cadastro"));
            cad.setUsuario(conex.getRs().getString("usuario_cadastro"));
            cad.setSenha(conex.getRs().getString("senha_cadastro"));
            cad.setConfsenha(conex.getRs().getString("confsenha_cadastro"));
            cad.setEmail(conex.getRs().getString("email_cadastro"));
            exibirCadastro();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro 'Pesquisa':\n" + ex.getMessage());
            limparTela();
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        /*l.ler();
        exibirCadastro(l.primeiro());*/
        try {
            String sql = ("update Cadastros set nome_cadastro=?,sobrenome_cadastro=?,usuario_cadastro=?,senha_cadastro=?,confsenha_cadastro=?,email_cadastro=? where cod_cadastro=?");
            PreparedStatement pst = conex.getConexaoBD().prepareStatement(sql);
            pst.setString(1, jTextFieldNome.getText());
            pst.setString(2, jTextFieldSobrenome.getText());
            pst.setString(3, jTextFieldUsuario.getText());
            pst.setString(4, jPasswordFieldSenha.getText());
            pst.setString(5, jPasswordFieldConfSenha.getText());
            pst.setString(6, jTextFieldEmail.getText());
            pst.setInt(7, Integer.parseInt(jTextFieldID.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Alterado com sucesso");
            jButtonNovoActionPerformed(evt);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro:\n" + ex.getMessage());
            limparTela();
        }
        preencherTabela("select * from Cadastros order by cod_cadastro");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        /*if (jTextFieldID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe um id válido");
            return;
        }
        if (l.excluir(Integer.parseInt(jTextFieldID.getText())) == null) {
            JOptionPane.showMessageDialog(this, "Cadastro não encontrado");
        } else {
            JOptionPane.showMessageDialog(this, "Cadastro excluído com sucesso ");
            if (l.Vazia() == true) {
                JOptionPane.showMessageDialog(this, "Lista vazia");
                limparTela();
            } else {
                exibirCadastro(l.atual());
            }
        }*/
        if (jTextFieldID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe um ID válido");
            limparTela();
            return;
        }        
        try {
            int resp = 0;
            resp = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
            if (resp == JOptionPane.YES_OPTION) {
                PreparedStatement pst = conex.getConexaoBD().prepareStatement("delete from Cadastros where cod_cadastro=?");
                pst.setInt(1, Integer.parseInt(jTextFieldID.getText()));
                pst.execute();
                JOptionPane.showMessageDialog(this, "Cadastro excluído com sucesso");
                jButtonNovoActionPerformed(evt);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cadastro não encontrado");
            limparTela();
        }
        preencherTabela("select * from Cadastros order by cod_cadastro");
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        /*String nome = jTextFieldNome.getText();
        String sobrenome = jTextFieldSobrenome.getText();
        String usuario = jTextFieldUsuario.getText();
        String senha = jPasswordFieldSenha.getText();
        String email = jTextFieldEmail.getText();
        int id = l.inserirNoFinal(nome, sobrenome, usuario, senha, email);
        jTextFieldID.setText(Integer.toString(id));*/
        limparTela();
        jButtonSalvar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldSobrenome.setEnabled(true);
        jTextFieldUsuario.setEnabled(true);
        jTextFieldID.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfSenha.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jButtonNovo.setEnabled(false);

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldSobrenome.setEnabled(true);
        jTextFieldUsuario.setEnabled(true);
        jTextFieldID.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfSenha.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        try {
            conex.executaSQL("select * from Cadastros");
            conex.getRs().first();
            jTextFieldNome.setText(conex.getRs().getString("nome_cadastro"));
            jTextFieldSobrenome.setText(conex.getRs().getString("sobrenome_cadastro"));
            jTextFieldUsuario.setText(conex.getRs().getString("usuario_cadastro"));
            jTextFieldID.setText(String.valueOf(conex.getRs().getString("cod_cadastro")));
            jPasswordFieldSenha.setText(conex.getRs().getString("senha_cadastro"));
            jPasswordFieldConfSenha.setText(conex.getRs().getString("confsenha_cadastro"));
            jTextFieldEmail.setText(conex.getRs().getString("email_cadastro"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro 'Primeiro':\n" + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldSobrenome.setEnabled(true);
        jTextFieldUsuario.setEnabled(true);
        jTextFieldID.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfSenha.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        try {
            conex.getRs().previous();
            jTextFieldNome.setText(conex.getRs().getString("nome_cadastro"));
            jTextFieldSobrenome.setText(conex.getRs().getString("sobrenome_cadastro"));
            jTextFieldUsuario.setText(conex.getRs().getString("usuario_cadastro"));
            jTextFieldID.setText(String.valueOf(conex.getRs().getString("cod_cadastro")));
            jPasswordFieldSenha.setText(conex.getRs().getString("senha_cadastro"));
            jPasswordFieldConfSenha.setText(conex.getRs().getString("confsenha_cadastro"));
            jTextFieldEmail.setText(conex.getRs().getString("email_cadastro"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro 'Anterior':\n" + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldSobrenome.setEnabled(true);
        jTextFieldUsuario.setEnabled(true);
        jTextFieldID.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfSenha.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        try {
            conex.getRs().next();
            jTextFieldNome.setText(conex.getRs().getString("nome_cadastro"));
            jTextFieldSobrenome.setText(conex.getRs().getString("sobrenome_cadastro"));
            jTextFieldUsuario.setText(conex.getRs().getString("usuario_cadastro"));
            jTextFieldID.setText(String.valueOf(conex.getRs().getString("cod_cadastro")));
            jPasswordFieldSenha.setText(conex.getRs().getString("senha_cadastro"));
            jPasswordFieldConfSenha.setText(conex.getRs().getString("confsenha_cadastro"));
            jTextFieldEmail.setText(conex.getRs().getString("email_cadastro"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro 'Próximo':\n" + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldSobrenome.setEnabled(true);
        jTextFieldUsuario.setEnabled(true);
        jTextFieldID.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfSenha.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        try {
            conex.executaSQL("select * from Cadastros");
            conex.getRs().last();
            jTextFieldNome.setText(conex.getRs().getString("nome_cadastro"));
            jTextFieldSobrenome.setText(conex.getRs().getString("sobrenome_cadastro"));
            jTextFieldUsuario.setText(conex.getRs().getString("usuario_cadastro"));
            jTextFieldID.setText(String.valueOf(conex.getRs().getString("cod_cadastro")));
            jPasswordFieldSenha.setText(conex.getRs().getString("senha_cadastro"));
            jPasswordFieldConfSenha.setText(conex.getRs().getString("confsenha_cadastro"));
            jTextFieldEmail.setText(conex.getRs().getString("email_cadastro"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro 'Último':\n" + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    public void preencherTabela(String sql) {

        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"ID", "Nome", "Sobrenome", "Usuário", "Senha", "Conf. Senha", "E-mail"};

        conex.executaSQL(sql);
        try {
            conex.getRs().first();
            do {
                dados.add(new Object[]{conex.getRs().getInt("cod_cadastro"), conex.getRs().getString("nome_cadastro"), conex.getRs().getString("sobrenome_cadastro"), conex.getRs().getString("usuario_cadastro"), conex.getRs().getString("senha_cadastro"), conex.getRs().getString("confsenha_cadastro"), conex.getRs().getString("email_cadastro")});
            } while (conex.getRs().next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro 'Peencher Tabela':\n" + ex.getMessage());
        }
        Tabela tabel = new Tabela(dados, Colunas);
        jTableCadastro.setModel(tabel);
        jTableCadastro.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableCadastro.getColumnModel().getColumn(0).setResizable(false);
        jTableCadastro.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTableCadastro.getColumnModel().getColumn(1).setResizable(false);
        jTableCadastro.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableCadastro.getColumnModel().getColumn(2).setResizable(false);
        jTableCadastro.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTableCadastro.getColumnModel().getColumn(3).setResizable(false);
        jTableCadastro.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableCadastro.getColumnModel().getColumn(4).setResizable(false);
        jTableCadastro.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTableCadastro.getColumnModel().getColumn(5).setResizable(false);
        jTableCadastro.getColumnModel().getColumn(6).setPreferredWidth(214);
        jTableCadastro.getColumnModel().getColumn(6).setResizable(false);
        jTableCadastro.getTableHeader().setReorderingAllowed(false);
        jTableCadastro.setAutoResizeMode(jTableCadastro.AUTO_RESIZE_OFF);
        jTableCadastro.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void exibirCadastro() {
        if (cad != null) {

            jTextFieldNome.setText(cad.getNome());
            jTextFieldSobrenome.setText(cad.getSobrenome());
            jTextFieldUsuario.setText(cad.getUsuario());
            jTextFieldID.setText(Integer.toString(cad.getId()));
            jPasswordFieldSenha.setText(cad.getSenha());
            jPasswordFieldConfSenha.setText("");
            jTextFieldEmail.setText(cad.getEmail());
        }
    }

    private boolean preencherObjeto() {

        cad.setNome(jTextFieldNome.getText());
        cad.setSobrenome(jTextFieldSobrenome.getText());
        cad.setUsuario(jTextFieldUsuario.getText());
        cad.setId(Integer.parseInt(jTextFieldID.getText()));
        cad.setSenha(jPasswordFieldSenha.getText());
        cad.setConfsenha(jPasswordFieldConfSenha.getText());
        cad.setEmail(jTextFieldEmail.getText());
        return true;
    }

    private boolean validarCampos() {

        if (jTextFieldNome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite um nome!!");
            jTextFieldNome.requestFocus();
            return false;
        }
        if (jTextFieldNome.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "Erro 'Nome':\nDigite no máximo 20 caracteres!!");
            jTextFieldNome.requestFocus();
            return false;
        }
        if (jTextFieldSobrenome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o sobrenome!!");
            jTextFieldSobrenome.requestFocus();
            return false;
        }
        if (jTextFieldSobrenome.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "Erro 'Sobrenome':\nDigite no máximo 20 caracteres!!");
            jTextFieldSobrenome.requestFocus();
            return false;
        }
        if (jTextFieldUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o usuário!!");
            jTextFieldUsuario.requestFocus();
            return false;
        }
        if (jTextFieldUsuario.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "Erro 'Usuário':\nDigite no máximo 20 caracteres!!");
            jTextFieldUsuario.requestFocus();
            return false;
        }
        if (jPasswordFieldSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a senha!!");
            jPasswordFieldSenha.requestFocus();
            return false;
        }
        if (jPasswordFieldSenha.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "Erro 'Senha':\nDigite no máximo 20 caracteres!!");
            jPasswordFieldSenha.requestFocus();
            return false;
        }
        if (jPasswordFieldConfSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Confirme a senha!!");
            jPasswordFieldConfSenha.requestFocus();
            return false;
        }
        if (jPasswordFieldConfSenha.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "Digite no máximo 20 caracteres!!");
            jPasswordFieldConfSenha.requestFocus();
            return false;
        }
        if(jPasswordFieldSenha.getText() == null ? jPasswordFieldConfSenha.getText() != null : !jPasswordFieldSenha.getText().equals(jPasswordFieldConfSenha.getText())){
            JOptionPane.showMessageDialog(this, "Senha incorreta!!");
            jPasswordFieldConfSenha.requestFocus();
            return false;
        }
        if (jTextFieldEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o e-mail!!");
            jTextFieldEmail.requestFocus();
            return false;
        }
        if (jTextFieldEmail.getText().length() > 30) {
            JOptionPane.showMessageDialog(this, "Erro 'E-mail':\nDigite no máximo 30 caracteres!!");
            jTextFieldEmail.requestFocus();
            return false;
        }
        return true;
    }

    private void limparTela() {

        jTextFieldNome.setText("");
        jTextFieldSobrenome.setText("");
        jTextFieldUsuario.setText("");
        jTextFieldID.setText("0");
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfSenha.setText("");
        jTextFieldEmail.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCadUsu;
    private javax.swing.JLabel jLabelConfSenha;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFundoCadastro;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSobrenome;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldConfSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCadastro;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSobrenome;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
